package top.capiudor.security.entity;

import java.io.Serializable;

public class Resource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.res_name
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.res_url
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.res_jurisdiction
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String resJurisdiction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.res_name
     *
     * @return the value of resource.res_name
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.res_name
     *
     * @param resName the value for resource.res_name
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.res_url
     *
     * @return the value of resource.res_url
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.res_url
     *
     * @param resUrl the value for resource.res_url
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.res_jurisdiction
     *
     * @return the value of resource.res_jurisdiction
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getResJurisdiction() {
        return resJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.res_jurisdiction
     *
     * @param resJurisdiction the value for resource.res_jurisdiction
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setResJurisdiction(String resJurisdiction) {
        this.resJurisdiction = resJurisdiction == null ? null : resJurisdiction.trim();
    }
}