package top.capiudor.security.entity;

import java.io.Serializable;

public class ResourceRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_role.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_role.role_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_role.res_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_role.id
     *
     * @return the value of resource_role.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_role.id
     *
     * @param id the value for resource_role.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_role.role_id
     *
     * @return the value of resource_role.role_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_role.role_id
     *
     * @param roleId the value for resource_role.role_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_role.res_id
     *
     * @return the value of resource_role.res_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_role.res_id
     *
     * @param resId the value for resource_role.res_id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }
}