package top.capiudor.security.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.useranme
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String useranme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headImg
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private String headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.useranme
     *
     * @return the value of user.useranme
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getUseranme() {
        return useranme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.useranme
     *
     * @param useranme the value for user.useranme
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setUseranme(String useranme) {
        this.useranme = useranme == null ? null : useranme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headImg
     *
     * @return the value of user.headImg
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headImg
     *
     * @param headimg the value for user.headImg
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }
}