package top.capiudor.security.dao;

import top.capiudor.security.entity.ResourceRole;

import java.util.List;

public interface ResourceRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    int insert(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    int insertSelective(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    ResourceRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    int updateByPrimaryKeySelective(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role
     *
     * @mbggenerated Tue Dec 31 15:09:44 CST 2019
     */
    int updateByPrimaryKey(ResourceRole record);

    List<ResourceRole> selectAll();
}